/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaApp */

#ifndef _Included_JavaApp
#define _Included_JavaApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaApp
 * Method:    showResult
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaApp_showResult(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
