/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_Main */

#ifndef _Included_Java_Main
#define _Included_Java_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_Main
 * Method:    func_init_enclave_ra
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_Java_1Main_func_1init_1enclave_1ra
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Java_Main
 * Method:    config_extended_ID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Java_1Main_config_1extended_1ID
  (JNIEnv *, jobject, jint);

/*
 * Class:     Java_Main
 * Method:    send_MSG0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Java_1Main_send_1MSG0
  (JNIEnv *, jobject, jint);

/*
 * Class:     Java_Main
 * Method:    send_MSG1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Java_1Main_send_1MSG1
  (JNIEnv *, jobject, jint);

/*
 * Class:     Java_Main
 * Method:    verifyMSG2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Java_1Main_verifyMSG2
  (JNIEnv *, jobject);

/*
 * Class:     Java_Main
 * Method:    send_MSG3
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Java_1Main_send_1MSG3
  (JNIEnv *, jobject, jint);

/*
 * Class:     Java_Main
 * Method:    verifyMSG3_and_PutINEnclave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Java_1Main_verifyMSG3_1and_1PutINEnclave
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
