/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaSGX */

#ifndef _Included_JavaSGX
#define _Included_JavaSGX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaSGX
 * Method:    sgx_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaSGX_sgx_1init
  (JNIEnv *, jobject);

/*
 * Class:     JavaSGX
 * Method:    sgx_enc
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaSGX_sgx_1enc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaSGX
 * Method:    sgx_dec
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaSGX_sgx_1dec
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     JavaSGX
 * Method:    sgx_add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaSGX_sgx_1add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaSGX
 * Method:    sgx_add_enc
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaSGX_sgx_1add_1enc
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     JavaSGX
 * Method:    sgx_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaSGX_sgx_1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
